defaults:
  - math_operator: addition
  - override hydra/launcher: submitit_slurm
  - _self_
  - seed_mode: array

# training defaults from TrainableTransformer.add_model_specific_args
batchsize: 0
n_layers: 2
n_heads: 4
d_model: 128
dropout: 0.0
weight_noise: 0.0
non_linearity: relu
max_context_len: 50
operand_length: null
train_data_pct: 5
warmup_steps: 10
anneal_lr_steps: 100000
anneal_lr: false
max_lr: 1e-3
weight_decay: 0
weight_decay_kind: to_zero
noise_factor: 0
save_activations: false
save_outputs: false
logdir: ${hydra:runtime.output_dir}
datadir: data

# data paths
# datasets_file: datasets/166k_datasets.yaml
# single_array_across_datasets: true
# dataset_index: ${env:AL_DATASET_INDEX,0}
# dataset_name: ${dataset_field:${datasets_file},${dataset_index},name}
# metadata_path: ${dataset_field:${datasets_file},${dataset_index},metadata_path}
# embedding_dir: ${dataset_field:${datasets_file},${dataset_index},embedding_dir}
# embedding_model: 1m_alphagenome_1bp_embeddings_kneedle
# embedding_path: ${embedding_dir}/${embedding_model}.npz
# subset_ids_path: ${dataset_field:${datasets_file},${dataset_index},subset_ids_path,null}
# base directory for Hydra run outputs (can be overridden in config/CLI)
results_root_dir: /share/home/wangzitongLab/liuxuyin/grok_study/results

# number of random seeds to run for each active learning experiment
num_seeds_per_job: 3
seed_start: 0
parallelize_seeds: true

# active learning settings
al_settings:
  # batch_size: 12
  # starting_batch_size: 12
  # max_rounds: 29 # not including the initial selection
  # feature_transforms: ${feature_transforms}
  # target_transforms: ${target_transforms}
  output_dir: ${hydra:runtime.output_dir}
  # query_strategy: ${query_strategy}
  # label_key: "Fold Change (Induced/Basal)"
  # predictor: ${predictor}
  # initial_selection_strategy: ${initial_selection_strategy}
  seed: 0

# hydra settings
hydra:
  job:
    config:
      override_dirname:
        kv_sep: "="
        item_sep: "|"
        exclude_keys:
          - al_settings.seed
  sweep:
    dir: ${results_root_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  sweeper: # multirun mode sweeps over these parameters
    params:
      math_operator: addition
      weight_noise: 0.0,0.1,0.2,0.3,0.5
      train_data_pct: 5,20,30
    
  launcher:
    setup:
      - source ~/miniconda3/etc/profile.d/conda.sh
      - conda activate grok
    timeout_min: 180
    # everything below is used only for submitting jobs to the cluster
    partition: wangzitong
    cpus_per_task: 1
    qos: gpu-limit
    gres: gpu:1
    mem_per_cpu: 16GB
    additional_parameters:
      nodelist: xnode104
    submitit_folder: slurm_logs
